name: flatpak

on:
  push:
  pull_request:

jobs:
  build-linux-flatpak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------
      # 安装  Node
      # -----------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install --loglevel=info

      - name: Fetch assets
        run: npm run fetch

      # -----------------------------
      # 安装  Flatpak & Runtime
      # -----------------------------
      - name: Install Flatpak & Runtimes
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

          sudo flatpak remote-add --if-not-exists --system flathub \
            https://flathub.org/repo/flathub.flatpakrepo

          sudo flatpak install -y --noninteractive --system flathub \
            org.freedesktop.Platform/x86_64/24.08 \
            org.freedesktop.Sdk/x86_64/24.08 \
            org.electronjs.Electron2.BaseApp/x86_64/24.08

          echo "========== INSTALLED SYSTEM RUNTIMES =========="
          sudo flatpak list --system

      # -----------------------------
      # 构建  Linux + Flatpak
      # -----------------------------
      - name: Build Linux + Flatpak
        run: |
          npm run build:linux

      # -----------------------------
      # 上传  Flatpak 构建产物
      # -----------------------------
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-flatpak-x64
          path: dist-linux/*.flatpak
          retention-days: 1