name: flatpak

on:
  workflow_dispatch:

jobs:

  flatpak:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x64
            arch: x64
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install dependencies
      run: |
        rm -f package-lock.json
        npm install --loglevel=info
  
    - name: Fetch
      run: npm run fetch


    - name: Install Flatpak & Runtime
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y --noninteractive flathub org.freedesktop.Platform//24.08
        flatpak --user install -y --noninteractive flathub org.freedesktop.Sdk//24.08
        flatpak --user install -y --noninteractive flathub org.electronjs.Electron2.BaseApp//24.08

    - name: Build Linux app
      run: npm run build:linux

    - name: Prepare Flatpak sources
      run: |
        cp dist-linux/linux-unpacked/astraeditor-desktop dist-linux/

    - name: Build Flatpak
      run: |
        flatpak-builder --repo=repo build-dir flatpak/org.astraeditor.AstraEditor.yml --force-clean
        flatpak build-bundle repo AstraEditor.flatpak org.astraeditor.AstraEditor
        mkdir -p dist
        mv AstraEditor.flatpak dist/

    - uses: actions/upload-artifact@v4
      with:
        name: linux-flatpak-x64
        path: dist/*.flatpak
        retention-days: 1
